version: '3'

services:
  concourse-db:
    image: postgres
    environment:
      POSTGRES_DB: concourse
      POSTGRES_PASSWORD: concourse_pass
      POSTGRES_USER: concourse_user
      PGDATA: /database

  concourse:
    image: concourse/concourse
    command: quickstart
    privileged: true
    depends_on: [concourse-db,keycloak]
    ports: ["8080:8080"]
    environment:
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_PASSWORD: concourse_pass
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_EXTERNAL_URL: http://cc.10.145.61.6.xip.io:8080/
      CONCOURSE_ADD_LOCAL_USER: test:test
      CONCOURSE_MAIN_TEAM_LOCAL_USER: test
      CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER: overlay
      CONCOURSE_MAIN_TEAM_OIDC_GROUP: admin
      CONCOURSE_OIDC_DISPLAY_NAME: ConcourseCI
      CONCOURSE_OIDC_CLIENT_ID: concourse-ci
      CONCOURSE_OIDC_CLIENT_SECRET: f25bcc8f-7d94-43a2-ac2e-86d506d02748
      CONCOURSE_OIDC_ISSUER: http://10.145.61.6.xip.io:8180/auth/realms/concourse-ci
  keycloak:
    image: jboss/keycloak:7.0.1
    container_name: keycloak
    restart: always
    ports:
      - 8180:8180
    environment:
      - KEYCLOAK_USER=kcadmin
      - KEYCLOAK_PASSWORD=kcadmin
    command: >
      -b 0.0.0.0
      -Djboss.http.port=8180
    tty: true