resources:
- name: testApp
  type: git
  source: { uri: "https://github.com/Yoshinori-Koide-PRO/concourse-smee-ci"}
  check_every: 8h
  webhook_token: test_token

jobs:
- name: hello-world
  plan:
  - get: testApp
    trigger: true
  - task: say-hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: alpine}
      run:
        path: echo
        args: ["Hello, world!"]